### ISSUE TITLE
Add Solr configuration selector

### ISSUE THREAD

**Issue by irnnr** [TYPO3-Solr/ext-tika#16]
In the Extension Manager configuration view:

If EXT:solr is installed offer a custom field type to select the Solr server connection instead of having to enter the host, port, and path.

**Comment by dkd-kaehm** [comment]
Rejecting, because EXT:tika's connection settings are site independent and should stay that way.
The users can set the connection by copying 4 values in the form or better provide them by (.dot-) ENV variables.
IMHO there are no needs for some actions there.

See: https://github.com/helhum/dotenv-connector
https://github.com/vlucas/phpdotenv
